/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fc",
        "inverse-on-surface": "#9a9da0",
        "primary-container": "#78c6fd",
        "tertiary": "#585c85",
        "secondary-fixed-dim": "#c5d7e7",
        "on-secondary-fixed-variant": "#4d5d6b",
        "on-primary": "#f5f9ff",
        "inverse-surface": "#0b0f11",
        "surface-dim": "#d4dbe1",
        "on-secondary-container": "#435461",
        "on-primary-fixed": "#00283d",
        "tertiary-container": "#cbcefe",
        "on-tertiary-fixed-variant": "#4a4e76",
        "error-dim": "#67040d",
        "on-secondary-fixed": "#31414e",
        "outline": "#747c81",
        "primary-dim": "#005981",
        "surface-container": "#e9eef3",
        "primary-fixed-dim": "#69b8ee",
        "on-error": "#fff7f6",
        "surface-variant": "#dce3e9",
        "on-secondary": "#f5f9ff",
        "on-tertiary-fixed": "#2d3157",
        "inverse-primary": "#78c6fd",
        "secondary-container": "#d3e5f5",
        "primary": "#006592",
        "on-surface": "#2c3338",
        "secondary-fixed": "#d3e5f5",
        "outline-variant": "#acb3b9",
        "primary-fixed": "#78c6fd",
        "surface-container-low": "#f0f4f8",
        "surface-bright": "#f7f9fc",
        "on-tertiary": "#fbf8ff",
        "surface-tint": "#006592",
        "on-surface-variant": "#596065",
        "error": "#a83836",
        "on-tertiary-container": "#40446c",
        "on-background": "#2c3338",
        "error-container": "#fa746f",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dce3e9",
        "surface-container-high": "#e3e9ee",
        "tertiary-fixed-dim": "#bdc0ef",
        "on-error-container": "#6e0a12",
        "on-primary-container": "#003f5d",
        "tertiary-dim": "#4c5078",
        "tertiary-fixed": "#cbcefe",
        "on-primary-fixed-variant": "#00486a",
        "secondary": "#50616f",
        "secondary-dim": "#445563",
        "background": "#f7f9fc"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
